### ISSUE TITLE
cluster: implement NodeMeta as gossip message

### ISSUE THREAD

**Issue by ijsong** [xsdb/xsdb#1]
NodeMeta is message to communicate with xsdb nodes by gossip.

**Comment by ijsong** [comment]
NodeMeta contains whole metadata about node and partition. Thus it is easy to entangle node and partition. I am focusing separate node and partition.

**Comment by ijsong** [comment]
NodeMeta should have timestamp, because order between gossip messages is important. Unfortunately, memberlist which we are using to implement gossip seems to have no consideration about order of events. It seems that HLC (Hybrid Logical Clock) can work.

**Comment by hungryjang** [comment]
@ijsong I do not think HLC is needed if there is a timestamp on each partitionDescriptor.

**Comment by ijsong** [comment]
@hungryjang Yes, you're right. I think it is sufficient for partition to keep local timestamp such as unix time. However, we are planning to implement HLC to track distributed events like MPT. Thus, it is not big deal, maybe.
In this issue, it would be better to use local timestamp. HLC is separate issue.

**Comment by ijsong** [comment]
I just closed this issue and merged PR #2. This is starting point.
